### ISSUE TITLE
SteamVR Error

### ISSUE THREAD

**Issue by KupchinskiyVasiliy** [r57zone/Half-Life-Alyx-novr#1]
**Videocard**: NVIDIA GeForce GT 620M
**Driver:** NVIDIA 391.35-notebook-win10-64bit-international-whql

![image](https://user-images.githubusercontent.com/22072950/78324678-8fbd0200-759f-11ea-9f04-0223891386cc.png)

When I try to launch Half-Life: Alyx - I got additional error.
![image](https://user-images.githubusercontent.com/22072950/78324840-0eb23a80-75a0-11ea-8bcf-3ffaf07e396c.png)

**Comment by KupchinskiyVasiliy** [comment]
А да, драйвер версии 0.2

**Comment by r57zone** [comment]
А в steamvr.vrsettings разрешение такое же стоит? Можете прислать конфиг? Монитор один?

**Comment by KupchinskiyVasiliy** [comment]
2 монитора - один ноутбучный встроенный, второй подключенный внешний. Ноутбук закрыт - работает один внешний монитор.

У внешнего монитора разрешение 1280x1024 установлено. При этом играть пытаюсь на 1024x768 для увеличения фпс (ноут слабенький).
Т.е. игру запускаю с 1024x768, и в default.vrsettings стоит 1024x768.

steamvr.vrsettings не нашел где, есть только default.vrsettings:
```
{
	"tovr" : {
		"DebugMode" : false,
		"Stereo" : false,
		"DistanceBetweenEyes" : 0,
		"DistortionK1" : 0,
		"DistortionK2" : 0,
		"ScreenOffsetX" : 0,
		"ZoomHeight" : 1,
		"ZoomWidth" : 1,
		"displayFrequency" : 60,
		"renderHeight" : 1080,
		"renderWidth" : 1080,
		"secondsFromVsyncToPhotons" : 0.004999999888241291,
		"serialNumber" : "1000",
		"windowHeight" : 768,
		"windowWidth" : 1024,
		"windowX" : 0,
		"windowY" : 0
   }
}
```

**Comment by r57zone** [comment]
Кажется понял, разрешение всегда нужно устанавливать как на мониторе, для увеличения FPS снижается renderWidth и renderHeight (типа фактическое изображение), а windowWidth и windowHeight просто размер окна. 
Еще можно попробовать изменить "DebugMode" на true, вместо false, тогда должно заработать в маленьком окошке.

**Comment by KupchinskiyVasiliy** [comment]
Попёрло. Вторая ошибка тоже исчезла.
