### ISSUE TITLE
Is it possible to use this IN VR? 

### ISSUE THREAD

**Issue by officialnochill** [r57zone/Half-Life-Alyx-novr#11]
I want to combine this with the LeapMotion driver plus a hand controller that binds some of the actions that your driver provides... If not possible then this is a suggestion :)

**Comment by r57zone** [comment]
Leapmotion is cool, but these things are incompatible. My HalfLife driver is completely tailored for the keyboard and mouse. Leapmotion is suitable as getting posioning for controllers, have some Leapmotion SteamVR drivers were, maybe they can help you.
