### ISSUE TITLE
is or will die - 2nd wheel mission (help)

### ISSUE THREAD

**Issue by hamitcagdas** [r57zone/Half-Life-Alyx-novr#12]
I cant place wheel for 2hours :D what's wrong with this wheel

![image](https://user-images.githubusercontent.com/53727346/79374692-2bffe500-7f60-11ea-8c2f-961a250ffbb7.png)

**Comment by r57zone** [comment]
Grab the wheel with one hand, lower your hand (PageUp and PageDown) to the pin level and rotate (U, J, H, K), then move it forward.

**Comment by hamitcagdas** [comment]
nope doesn't work for real.  I am even fit it is like 100% correct it passes behind the wall.

![image](https://user-images.githubusercontent.com/53727346/79405878-3b058800-7f9e-11ea-89bb-f2649dbe9ed0.png)

I go straight to fit the wheel and it's getting inside wall as redlined

**Comment by r57zone** [comment]
https://youtu.be/PRvJlJEwujs?t=119

**Comment by hamitcagdas** [comment]
maybe the main problem is I can't move my right hand forward as you do in video and near enter I don't have your button my keyboard Turkish - Q can you check it on the internet and tell me which button it is. near enter button like in keyboard you use don't make this movement my left-hand in-game moving with the right hand so I can't find that button. to stop make movements with 1 hand

![image](https://user-images.githubusercontent.com/53727346/79430790-22af6080-7fd2-11ea-879c-b3b7524cb711.png)

only able to do it with the insert button and it moves two hands forward. and **still not attached**

![image](https://user-images.githubusercontent.com/53727346/79431119-a9643d80-7fd2-11ea-9cec-9eaca5488b79.png)

tried maybe 100 times :D

**Comment by r57zone** [comment]
Try to take with your left hand (left and right mouse button) and move it separately from your right hand. Straighten with U J H K so that the wheel is upright.

**Comment by r57zone** [comment]
If it doesn’t work, send me a saves

**Comment by hamitcagdas** [comment]
https://www.zipshare.com/download/e2FyY2hpdmVJZDowNDM0NWFkYy0wYjA1LTRmMDYtODBmZS1jODJjNmVjMmE1Mjh9

here

**Comment by r57zone** [comment]
Checked without VR and in VR. Dont work. This seems to be a bug of the game, because in VR it also doesn’t go around. Try starting the third chapter again or loading early saves.
