### ISSUE TITLE
хелп

### ISSUE THREAD

**Issue by QzoneX** [r57zone/Half-Life-Alyx-novr#13]
Ребят может кто помочь, два часа уже пытаюсь пройти это место, ни как не получается прокрутить..  https://steamuserimages-a.akamaihd.net/ugc/1011563971412018744/D5B2F563040675528D54743E031F9D6D6A50D0C9/

может есть у кого сохранение перед открытием люка? С пройденным шаром этим я уже с ума скоро сойду))

**Comment by r57zone** [comment]
Правым шифтом можно захватить и немного передвенуть, а потом двигаешь не спеша. Можно переключиться в режим прицеливания или лазера, чтобы удобнее было, также опускаться и подниматься.

**Comment by QzoneX** [comment]
Да я там что то накрутил у меня теперь даже руки в исходное положение не ставятся, левая рука вообще не пойми куда уехала и зажата в кулак, как вернуть не понятно(

**Comment by QzoneX** [comment]
Прост этот шар вместе со мной крутится, вверх вниз он тоже как и я( он не стоит на месте..

**Comment by QzoneX** [comment]
О получилось, СПАСИБО!!

**Comment by QzoneX** [comment]
А не подскажешь на какие кнопки скрины делать?

**Comment by r57zone** [comment]
В следующих версиях добавлю.
