### ISSUE TITLE
Слишком быстрая анимация 

### ISSUE THREAD

**Issue by Abirvalg0000** [r57zone/Half-Life-Alyx-novr#14]
Зомби носятся как ненормальные и диалоги пролетают, что и прочесть не успеваешь( в Общем ВСЯ анимация у очень быстрая.. пробовал снизить ФПС с 60 до 30 - стало чуть лучше но не особо... Подскажите как исправить пожалуйста
Пробовал и пиратку и лицензию.. Одинаковая ситуация(

**Comment by r57zone** [comment]
Закрыть всё, запустить сначала SteamVR и только потом игру.

**Comment by Abirvalg0000** [comment]
Не помогло( страйдеры в самом начале игры отыгрывают всю анимацию за 10 секунд и уходят( 
Можно еще что то попробовать сделать?

**Comment by r57zone** [comment]
Не знаю даже, но это врятле связано с драйвером.

**Comment by Abirvalg0000** [comment]
Поставил драйвера на видио карту поновее и все заработало) Спасибо
