### ISSUE TITLE
перезарядка

### ISSUE THREAD

**Issue by QzoneX** [r57zone/Half-Life-Alyx-novr#15]
Numpad "." или ">" на эти кнопки должна выпадать обойма? Прост ни чего не происходит.. различными движениями тож не получается вытащить.. один раз случайно как то получилось.. как наладить этот процесс?)

**Comment by r57zone** [comment]
Numpad 0 или <

**Comment by QzoneX** [comment]
спс нажимал просто 0)

**Comment by QzoneX** [comment]
Теперь с дробовиком проблема) как его перезарядить? и вытащить из рюкзака патроны для него. Затвор открывается но патрики из руки не вставляются как в пистолет. Застрял в 3 главе из за этого, после колеса, над зарядить дробовик. чтоб дальше продвинутся..

**Comment by r57zone** [comment]
Взять в руку, поднести в нужно место (правая кнопка мыши) и приподнять кнопками. Кучу видео на ютубе https://youtu.be/K_I5fm-cT6Y?t=389
