### ISSUE TITLE
Редактирование привязки клавиш

### ISSUE THREAD

**Issue by ghost** [r57zone/Half-Life-Alyx-novr#16]
сегодня увидел пост про "редактирование привязки клавиш"
в папке  \TrueOpenVR\Settings\Drivers\ файл HalfLifeAlyx.ini отсутствует.
обновил файл HalfLifeAlyx64.dll на версию 0.7.4.1
запустил игру, но файл HalfLifeAlyx.ini все равно не появляется...

**Comment by ghost** [comment]
сейчас обновил файл HalfLifeAlyx64.dll на версию 0.7.4.2
файл HalfLifeAlyx.ini по прежнему не появляется...

**Comment by r57zone** [comment]
Последняя версия пока только на бусти и патреон
