### ISSUE TITLE
Бесконечная загрузка сохранений

### ISSUE THREAD

**Issue by Half-Life-Lover** [r57zone/Half-Life-Alyx-novr#18]
После установки драйвера самой новой версии(вроде 7.4.2)все работает нормально но при загрузке сохранений они бесконечно грузятся.Раньше было подобное но это из-за того что халва зависала и нужно было перезпустить ёё.Сейчас же данный метод никак не помогает,жать пробовал.

**Comment by r57zone** [comment]
Замена драйвера никак не может влиять на загрузку или не загрузку игры, можете проверить заменив более старой версией. Драйвер никак не связан с игрой, он только дает данные о фейковых контроллера и шлеме.

Я на всякий перепроверил только что и все грузится.

Решения могут быть следующими: перезагрузить пк, отключить фоновые программы (utorrent и прочие, которые могут грузить жесткий диск).
