### ISSUE TITLE
Mouse control lost

### ISSUE THREAD

**Issue by KupchinskiyVasiliy** [r57zone/Half-Life-Alyx-novr#2]
Mouse control lost if SteamVR show message "Videodriver should be updated".

Steps for reproduce:
1. Run SteamVR or Half-Life: Alyx
2. Wait for videodriver outdated message.
3. Try move mouse pointer to "Cancel" button - you can't do this because mouse is hooked by driver.
4. Okay, Ctrl+Shift+Esc -> UAC window (Yes) -> mouse hook released -> click "Cancel" at videodriver outdated message box.
5. Alt+Tab -> Back to Headset window -> try to rotate with mouse - can't do this.

![image](https://user-images.githubusercontent.com/22072950/78347534-d83de500-75ca-11ea-9823-e7842805fa34.png)

**Comment by KupchinskiyVasiliy** [comment]
Драйвер стоит последний поддерживаемый, но SteamVR упорно ругается.

**Comment by r57zone** [comment]
**En:** Esc turns centering off and F7 turns back on.
1. First, press Esc, close the extra windows.
2. Press F7, switch the window and play.

Or you can return debugmode to true.
The driver version is probably a SteamVR bug and it seems that SteamVR does not work in any way.


**Ru:** Esc выключает центрирование, а F7 включает обратно.
1. Сначала жмем Esc, закрываем лишние окошки.
2. Жмем F7, переключем окно и играем.

Или можно вернуть debugmode на true.
Версия драйвера вероятно баг SteamVR и вроде не мешает никак работает SteamVR.
