### ISSUE TITLE
Screen is not attached to VR screen.

### ISSUE THREAD

**Issue by eminem0091** [r57zone/Half-Life-Alyx-novr#20]
https://www.youtube.com/watch?v=G3lBHgdhcFI

I always need to restart whole game. When I hold ">" it looks like it again working but when I unhold ">" problem will came back :(

How to fix this please?

**Comment by eminem0091** [comment]
Its random. When I restart game it came back to normal. But after playing a while it again happen :(

**Comment by eminem0091** [comment]
oh... it can be fixed by this
hold shift + ">"

**Comment by r57zone** [comment]
Try the older version, if it is the same, then the problem is not in the driver.

**Comment by hamitcagdas** [comment]
hi i didnt change anything last 1 week and same error happens to me today. anything about steam VR updated yesterday. can be main problem.

**Comment by hamitcagdas** [comment]
hi, I didn't change anything last 1 week and the same error happens to me today. anything about steam VR updated yesterday. can be the main problem.

**Comment by r57zone** [comment]
Related - https://github.com/r57zone/Half-Life-Alyx-novr/issues/23

**Comment by r57zone** [comment]
@hamitcagdas Can you check an older version? Do you run SteamVR and only then the game? Does this just happen on SteamVR? Could you just be in SteamVR for some time (for example, in SteamVR Room)?
