### ISSUE TITLE
Steam vr ошибка 422

### ISSUE THREAD

**Issue by valeradcp** [r57zone/Half-Life-Alyx-novr#21]
Установил всё как положено, конфиг настроил,драйвер поставил, труопенвр в правильной папке
Стим вр пишет ошибку 422, Смотрел в закрытых проблемах, пробовал что-то менять в конфиге, всё равно ошибка 422
![Безымянный](https://user-images.githubusercontent.com/42435578/79791728-774a3700-8356-11ea-8cc1-ba9651af7524.png)
![Безымянный2](https://user-images.githubusercontent.com/42435578/79791738-79ac9100-8356-11ea-8f71-798b21e193ad.png)
![Безымянный1](https://user-images.githubusercontent.com/42435578/79791744-7c0eeb00-8356-11ea-90c5-5e1014d2fa25.png)
![Безымянный3](https://user-images.githubusercontent.com/42435578/79791748-7d401800-8356-11ea-946c-883eef6328d7.png)

**Comment by r57zone** [comment]
Размеры окна соответствуют разрешению монитора? Если нет, то нужно поставить такое же разрешение, а рзамеры рендера можно уже изменять.

**Comment by valeradcp** [comment]
Размер окна соответствует разрешению монитора, пробовал их менять местами, всё равно не работает

**Comment by r57zone** [comment]
Попробуй "DebugMode" изменить на true. В TrueOpenVR выбран и применен "HafLifeAlyx64"?

**Comment by valeradcp** [comment]
в tovr выбран halflifealyx64, debug mode не помогает

**Comment by r57zone** [comment]
Тогда, если это возможно, то мне нужно видео процесса установки, чтобы я мог понять на каком этапе произошло что-то не так.
Кстати, есть 3 видео процесса установки, можно посмотреть еще [2](https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/SETUP2.RU.md#%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D0%B8)

**Comment by valeradcp** [comment]
я по ним и устанавливал

**Comment by valeradcp** [comment]
C:\Steam - папка стима
C:\Program Files\TrueOpenVR - папка tovr
G:\Half Life Alyx - папка hl:a
C:\Steam\steamapps\common\SteamVR\drivers\tovr\resources\settings - папка,где лежит конфиг
Может это что-то даст

**Comment by valeradcp** [comment]
[Bandicam.zip](https://github.com/r57zone/Half-Life-Alyx-novr/files/4505860/Bandicam.zip)
сделал два видео, в одном установка файлов, в другом показана сама проблема

**Comment by r57zone** [comment]
Вроде всё верно, странно.

Попробуй более старую версию, заработает ли она?
[HalfLifeAlyx64.0.3.2.driver.zip](https://github.com/r57zone/Half-Life-Alyx-novr/files/4506017/HalfLifeAlyx64.0.3.2.driver.zip)

**Comment by valeradcp** [comment]
Старая версия тоже не помогла

**Comment by valeradcp** [comment]
Может попробовать поставить старые версии trueopenvr?

**Comment by r57zone** [comment]
Нет, это не поможет. Не знаю, что делать.

**Comment by valeradcp** [comment]
а есть какая-нибудь лазейка запустить хла без стимвр?

**Comment by valeradcp** [comment]
driver.vdrivermanifest    trueopenvr
{
	"alwaysActivate": true,
	"name" : "tovr"
}
driver.vdrivermanifest  oculus
{
	"alwaysActivate": false,
	"name" : "oculus",
	"directory" : "",
	"resourceOnly" : false,
	
	"hmd_presence" :
	[
		"2833.*"
	]
}
Я заметил, что в первом случае не указана директория товр, может попробовать пошаманить немного?

**Comment by r57zone** [comment]
Без SteamVR работать не будет. Директорию указывать тоже не нужно. Вроде как я уже встречал подобные сообщения, возможно это связано с тем, что в "расширенном режиме" (обычный вывод в окне), какие-то проблемы у SteamVR с небольшими расширениями.

Попробуй еще renderWidth и renderHeight поменьше поставить, хотя это врятле поможет.

**Comment by valeradcp** [comment]
поставил 640 на 640, всё равно не помогло, видно не судьба

**Comment by URAKOLOUY5** [comment]
Та же самая проблема, и та же самая ошибка. Все сделал по туториалу.
**PS:** Я сменил разрешение на 1080p (разрешение монитора), и все стало нормально. Однако в таком разрешении моя видеокарта не способна играть нормально, мне приходится использовать 720p.

**Comment by r57zone** [comment]
Ru: Что если всем попробовать поставить разрешение 1920 на 1080 и в настройках уменьшить super sampling?

En: What if everyone tries to set the resolution to 1920 by 1080 and in the settings reduce super sampling?

**Comment by r57zone** [comment]
@URAKOLOUY5 можно уменьшить еще больше графику, у lowspecgamer есть видео.
