### ISSUE TITLE
Проблема с камерой

### ISSUE THREAD

**Issue by Que00** [r57zone/Half-Life-Alyx-novr#24]
При движении мышкой руки двигаются нормально, а камера с очень большой задержкой.
https://youtu.be/TqtccGiMc_Y

Возможно проблема в том, что я не понял седьмой пункт в гайде. 
> _7. Запускаем игру, выбираем игру и кликаем по ней, далее жмем ALT + TAB и переключаемся на "Headset Window" и кликаем. Окно состояния SteamVR и сообщения SteamVR можно скрыть._

Запускаю игру в стиме, делаю альт+таб на Headset Window, но там просто черный экран, тогда как в самой игре уже все загружается с картинкой и звуком.

Еще SteamVR выдает иногда такое:
![11](https://user-images.githubusercontent.com/64333497/80291616-bf52ca80-8757-11ea-881f-f90b6257e59e.jpg)
Не знаю влияет ли это на камеру, но в любом случае, при нажатии на включение этого режима, это окошко все равно выходит. 

Устанавливал всё по видеогайду, также прошелся еще по текстовому, ничего не упустил. Все лишние программы в трее выключены.

**Comment by r57zone** [comment]
Сообщения в SteamVR можно свернуть, чтобы они не мешали, ни на что не влияют, просто уведомления. Статус состояния тоже.
Нужно выбрать Headset Window и кликнуть по нему, чтобы окно в фокусе стало, чернота или краснота пропадет.

**Comment by Que00** [comment]
Понял в чем проблема. Играю в 4:3 на разрешении 1024х768. Выставил в файле default.vrsettings  значения "renderHeight" и "renderWidth" в соответствии со своим разрешением и все стало работать отлично.
