### ISSUE TITLE
bind controls to a joypad ?

### ISSUE THREAD

**Issue by momala454** [r57zone/Half-Life-Alyx-novr#25]
Would it be possible to map the controls to a dualshock 3 by example instead of mouse + keyboard ?
Could it be more natural to use or even possible ?

**Comment by r57zone** [comment]
Gamepads are not currently supported, however you can use the program: Controller Companion, XSpider and others to emulate a keyboard and mouse.

**Comment by momala454** [comment]
do you think there are enough buttons on a dualshock 3 to emulate all the functionnalities ?

**Comment by r57zone** [comment]
Probably not, but you can play on DualShock3, but go through some difficult moments on the keyboard and mouse.
