### ISSUE TITLE
сжать сердце хед краба

### ISSUE THREAD

**Issue by QzoneX** [r57zone/Half-Life-Alyx-novr#26]
Подскажите, а на как сжимать в руке предметы? (сердце) есть ачивка нужно сжать сердце хед краба, все перепробовал не сжимается..

**Comment by r57zone** [comment]
Можно попробовать нажать кнопку меню или кнопку захвата на контроллере, в раскладке по умолчанию это Enter для левого контроллера и Numpad 0 и Numpad "." (точка / del) для правого.
Если не работает, то наверное это ачивка для владельцев Valve Index (там на контроллерах что-то вроде кнопок, которые позволяют сжимать руки в игре, единственное на что они годятся).

**Comment by QzoneX** [comment]
ну да видать для индекса, сжимает, но ачивку не дает.. или не так сильно сжимает, жаль 1 единственная осталась не открытой(

**Comment by QzoneX** [comment]
О_О сработало!! раза с 20 засчитало, странно)

**Comment by r57zone** [comment]
А что нажимать нужно было? Кнопку меню или кнопку захвата?
