### ISSUE TITLE
Mouse not moving view in Spectator

### ISSUE THREAD

**Issue by mw308** [r57zone/Half-Life-Alyx-novr#27]
I've followed the video to use spectator mode but when I do the mouse cannot move the view.  The hands move and I can click etc, it's just the view that remains the same.  It work's fine in the VR view.  I'm using driver version 0.9.4, TrueOpenVR 0.7.2 portable and TrueOpenVR SteamVR 0.5.1.

**Comment by r57zone** [comment]
Is it possible that you accidentally pressed the Escape key? You can’t press it, because it intercepts the mouse. Instead of Escape you need to use the "~" key.

**Comment by mw308** [comment]
Checked that - if I press esc the mouse cursor disappears (if I haven’t run the hidecursor program) and the vr hands don’t move. Press esc again and the hands begin moving but the view stays put. When this happens the world disappears and reappears as if the viewpoint is changing.

**Comment by mw308** [comment]
Fixed - I was doing something wrong, sorry!
