### ISSUE TITLE
Как пройти данный момент в игре?

### ISSUE THREAD

**Issue by tawer2000** [r57zone/Half-Life-Alyx-novr#30]
Как пройти данный момент в игре? 
![unknown](https://user-images.githubusercontent.com/39432614/81395709-c9e46b00-912c-11ea-9c89-2fe14bfb2467.png)

**Comment by r57zone** [comment]
В видео показывалось, нужно зажать пробел и указать на место, тогда он телепортируется туда. Прыгать в игре нельзя, это делается телепортами на пробел. На youtube уже есть прохождения этим методом, а также есть информация в документации.
