### ISSUE TITLE
Как пройти данный момент?

### ISSUE THREAD

**Issue by tawer2000** [r57zone/Half-Life-Alyx-novr#32]
Не получается пройти делал все как на видео
![unknown](https://user-images.githubusercontent.com/39432614/81494465-d7772d80-92b1-11ea-99a2-496764c3b784.png)

**Comment by r57zone** [comment]
Если не получается нужно ввести в консоль команду, есть в инструкции на русском - https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/README.RU.md 
Эти инструкции я специально писал, чтобы не возникало вопросов.
