### ISSUE TITLE
После сегодняшнего обновления Steam VR перестал работать вместе с драйвером.

### ISSUE THREAD

**Issue by Evisneffo** [r57zone/Half-Life-Alyx-novr#33]
При запуске с драйвером, Steam VR просто не отвечает. 

Я переустанавливал и драйвер, и сам Steam VR. Ничего не помогло. 

Возможно это как-то связанно с тем, что у меня Windows 7?

До обновления 1.11, которое вышло сегодня раним утром, всё работало прекрасно, даже успел пройти пол игры с большим удовольствием.
![image](https://user-images.githubusercontent.com/62428089/82041608-41d10900-96ca-11ea-8b45-4e98e06392a7.png)

**Comment by r57zone** [comment]
Может быть, у 7ки закончилась поддержка и возможно Valve не проверили последний SteamVR на 7ке или прекратила поддержку 7ки.

**Comment by Evisneffo** [comment]
Да, так и есть. Перешёл на Windows 10, и игра снова заработала. Только появилась новая проблема, у меня сбитый прицел, если так можно выразиться. Вообще, руки не по центру, от смены правой или левой руки, ничего не меняется. То есть, например, когда я вхожу в прицел, оружие у меня слева.

**Comment by r57zone** [comment]
Пришли скрин. Если оружие слева нужно изменять главную руку на правую и перезапустиь игру.

**Comment by Evisneffo** [comment]
ля, я затупил. У меня итак всё время стояла правая рука (никогда левая не стояла, не знал что это), просто скошено влево (скрин с правой рукой но сбитым прицелом). 
Ну так вот, я поставил себе левую руку, и теперь из-за это управление перемешалось, и я не могу обратно поставить праву, так как можно поменять только в игре, а там я не могу выйти в меню, из-за того, что левая рука стоит и из-за неё управление сломалось.
![20200518112807_1](https://user-images.githubusercontent.com/62428089/82179295-c9ec2400-98ff-11ea-86d8-29db331680a7.jpg)

**Comment by Evisneffo** [comment]
Можно руку сменить через 'новую игру'? Она же будет во втором сейве?
А лучше было бы через консоль сменить

**Comment by Evisneffo** [comment]
Кстати, видел, где-то, у тебя параметры запуска для консоли, но забыл где. Можешь их сюда написать?

**Comment by Evisneffo** [comment]
![image](https://user-images.githubusercontent.com/62428089/82180484-70d1bf80-9902-11ea-966f-e8747e867b30.png)

**Comment by r57zone** [comment]
C:\Games\Half-Life Alyx\hlvr\SAVE\ в папках S0 - S9 удали файл personal.cfg

```
{
   "tovr" : {
      "DebugMode" : true,
      "Stereo" : true,
      "DistanceBetweenEyes" : 0,
      "DistortionK1" : 0,
      "DistortionK2" : 0,
      "ScreenOffsetX" : 0,
      "ZoomHeight" : 1,
      "ZoomWidth" : 1,
      "displayFrequency" : 0,
      "FOV" : 110,
      "renderHeight" : 1920,
      "renderWidth" : 1920,
      "secondsFromVsyncToPhotons" : 0.004999999888241291,
      "serialNumber" : "1000",
      "windowHeight" : 1080,
      "windowWidth" : 1920,
      "windowX" : 0,
      "windowY" : 0
   }
}

```

**Comment by Evisneffo** [comment]
Вообщем, я вернул правую руку, но мне бы их сдвинуть вправо, и збс было бы.

**Comment by r57zone** [comment]
Теперь как на видео? Сдвинуть влево нельзя

**Comment by Evisneffo** [comment]
https://user-images.githubusercontent.com/62428089/82179295-c9ec2400-98ff-11ea-86d8-29db331680a7.jpg У меня так же, как и на скриншоте который я уже кидал. На этом скриншоте у меня стоит управление WASD и режим зрителя. Также, на этом скриншоте я зажал ПКМ (вошёл в прицел) и он у меня не в центре экрана. А в остальном, вроде всё в порядке.

**Comment by r57zone** [comment]
VRMode=0 в конфиге должно стоять, по умолчанию в них стоит 0.

**Comment by Evisneffo** [comment]
Всё, разобрался. Причина была в том, что у меня стоял правый глаз в настройках зрителя, поставил левый и всё чётенько стало!

Только после перехода с 7 на 10 виндовс у меня в игре упала производительность, но я думаю это уже лично мои проблемы. Спасибо и удачи Вам!
