### ISSUE TITLE
Режим наблюдателя

### ISSUE THREAD

**Issue by UnionOfUniverses** [r57zone/Half-Life-Alyx-novr#35]
Здравствуйте. У меня проблема с режимом наблюдателя. Так как в VR режиме я не смог добиться нормальных значений для сокрытия черных углов/линий при игре, то решил испробовать режим наблюдателя. К сожалению, я столкнулся с другой проблемой, еле поняв, как всё настроить. При движении мышкой, например, вправо, кисти Аликс перемещаются так, как это ожидалось, т.е. нормально. Но почему-то сама "голова" Аликс перемещается оооочень странно, а именно с тормозами и не полностью туда, куда я направил мышь. Я следовал полностью вашим инструкциями, что были на видео, связанном с настройкой режима наблюдателя, но вышло вот так...

**Comment by r57zone** [comment]
Здравствуйте, кажется это режим перестал работать после обновления, нужно либо использовать старую версию игру, либо использовать "Headset Window".

**Comment by UnionOfUniverses** [comment]
> Кажется это режим перестал работать после обновления, нужно либо использовать старую версию игру, либо использовать "Headset Window".

Вы имеете в виду, снова попробовать через режим VR? Блин, я пробовал те значения, что использовали или же предлагали вы, а именно 0.76 или 0.87, но результат не очень впечатлял, хотя у вас и другого моего знакомого почему-то было получше (но у меня монитор тоже 1920 на 1080, из-за чего я не могу понять, почему эти углы так мешают даже при оптимальных значениях). Я делал значения, которые меньше, чем 0.7, и было более-менее удобно, но с графиков что-то странное происходило, как будто-то мыльное немного, из-за чего неприятно. Это связано с масштабированием? Если да, то что надо сделать, чтобы оптимизировать?

**Comment by r57zone** [comment]
Да, обычный режим, немного мешают углы, но через какое-то время к ним привыкаешь. Главное, чтобы debugMode был выключен и видеокарта была более менее, тогда углы почти не будут мешать. 

Мыло потому что необходимо разрешение 1920 на 1920, но в режиме VR это не требуется, если масштабирование небольшое.

**Comment by UnionOfUniverses** [comment]
> Да, обычный режим, немного мешают углы, но через какое-то время к ним привыкаешь. Главное, чтобы debugMode был выключен и видеокарта была более менее, тогда углы почти не будут мешать.
> 
> Мыло потому что необходимо разрешение 1920 на 1920, но в режиме VR это не требуется, если масштабирование небольшое.

Ну, дебаг выключен, карта 1066. А что подразумевается под "небольшим масштабированием"? Я просто не очень понял.

**Comment by r57zone** [comment]
ZoomWidth, ZoomHeight - 0.9 и разрешение умноженное на x1,1.

**Comment by UnionOfUniverses** [comment]
> ZoomWidth, ZoomHeight - 0.9 и разрешение умноженное на x1,1.

Спасибо за пояснение. Ещё один небольшой вопрос. В HalfLifeAlyx.ini в самом начале есть параметр VRMode, равный нулю. Да, там написано пояснение, но проблема в том, что изменял значение параметра, но по изменениям в прицеливании я ничего не заметил.

**Comment by r57zone** [comment]
VRMode 1 немного изменяет углы только при прицеливании, это нужно для VR режима (Android, iOS или DIY VR шлем вместо монитора).

**Comment by UnionOfUniverses** [comment]
> VRMode 1 немного изменяет углы только при прицеливании, это нужно для VR режима (Android, iOS или DIY VR шлем вместо монитора).

Понял, спасибо.
