### ISSUE TITLE
NPCs and Enemies - Animating faster than normal.

### ISSUE THREAD

**Issue by Moofers** [r57zone/Half-Life-Alyx-novr#36]
Weird issue where all enemies are moving in fast forward.
I'm unsure what is causing this issue.

Works fine when not using this mod.

**Comment by r57zone** [comment]
Try to launch SteamVR first and only then the game.

Another guy [managed to fix](https://github.com/r57zone/Half-Life-Alyx-novr/issues/14) this by updating the video card driver.

**Comment by Moofers** [comment]
I'll update my drivers and try the steam vr method.

> 
> 
> Try to launch SteamVR first and only then the game.
> 
> Another guy [managed to fix](https://github.com/r57zone/Half-Life-Alyx-novr/issues/14) this by updating the video card driver.

**Comment by Moofers** [comment]
Afraid the solutions you provided didn't seem to work.
Only seems to be related to the spectator view.

**Comment by r57zone** [comment]
Then, you can play in the Headset Window mode. If you want to use the WASD key binding, add a keyboard layout in Windows, for example, Russian (or any other, where there is no symbol "S"), switch to it using Shift + Alt. After going through game, you can delete the language layout.

**Comment by Moofers** [comment]
Thanks for the help but it doesn't seem to help.
