### ISSUE TITLE
Насчет 11-ой главы

### ISSUE THREAD

**Issue by UnionOfUniverses** [r57zone/Half-Life-Alyx-novr#37]
Здравствуйте ещё раз. Появилась другая проблема, а именно с броском этих энергетических сфер. Я использовал клавишу End, так как по инструкции было написано, что именно на эту клавишу забиндин нормальный бросок именно этих сфер. И да, казалось бы, эти сферы бросаются с первого раза, вот только одного но. Они у меня бросались с первого раза именно в ту стенку, на которую смотрел, но при столкновении с Солдатами Альянса почему-то вероятность броска снижается. Я еле смог убить только одного или двух, и то это как-то рандомно вышло. Даже перебиндил для удобства, чтобы быстрее нажимать, но всё равно не помогло. Можно ли это как-то решить? Я могу даже попробовать снять, если вам сейчас не очень понятно.

**Comment by r57zone** [comment]
Привет, да в курсе этой проблемы, в VR тоже самое, по крайней мере на гидрах. Какие-то проблемы с самой игрой.

Убивать по одному, сохранятся и проходить дальше или использовать чит на неуязвимость.

**Comment by UnionOfUniverses** [comment]
> Привет, да в курсе этой проблемы, в VR тоже самое, по крайней мере на гидрах. Какие-то проблемы с самой игрой.
> 
> Убивать по одному, сохранятся и проходить дальше или использовать чит на неуязвимость.

Ладно, более-менее всё-таки получается, тогда и на этом спасибо всё равно. Если бы не вы, то даже не знаю, как бы я сыграл без ВиАр-девайсов.
