### ISSUE TITLE
My Steam VR does not recognize the VR headset

### ISSUE THREAD

**Issue by rendigua** [r57zone/Half-Life-Alyx-novr#39]
I don't have a VR device. I installed SteamVR and configured it according to the tutorial yesterday, and I entered the game. But today it prompts "Please plug in your VR headset". The game can't get in, I want to ask for help.
There is another pop-up error "SteamVR failed initialization with error code VRInitError Init HmdNotFound: "Hmd Not Found (108)"
Please verify SteamVR is properly installed and try again."

**Comment by r57zone** [comment]
1. Is SteamVR starting?
2. Are you using the latest driver 1.0.2?
3. Did you install how on [video](https://youtu.be/Uq12rW3DrKI)?
4. What is the resolution of your monitor?

It seems SteamVR doesn't work.

**Comment by rendigua** [comment]
> 1. SteamVR开始了吗？
> 2. 您是否正在使用最新的驱动程序1.0.2？
> 3. 您是否在[视频](https://youtu.be/Uq12rW3DrKI)上安装了[视频](https://youtu.be/Uq12rW3DrKI)？
> 4. 显示器的分辨率是多少？
> 
> 看来SteamVR不起作用。

Thanks, I later found out that it was caused by a new keyboard I replaced today, and I can use it after I switch back to the old keyboard.
