### ISSUE TITLE
Doesnt work.

### ISSUE THREAD

**Issue by MixailTheDumbass** [r57zone/Half-Life-Alyx-novr#40]
Whatever I tried, it doesnt work. I tried to do it but I just got an infinite Valve loading intro in HLA. Does anybody know how to fix this?

**Comment by r57zone** [comment]
Are you using an unlicensed version? In unlicensed one of the cracks breaks the game. Endless download is a bug of the game (possibly a pirated one with one of the cracks) and has nothing to do with the non vr driver.

**Comment by MixailTheDumbass** [comment]
Yes. I have issues with the unlicensed version because I cant pay 1000rub for HLA. Like, seriously. So do I either buy HLA or just try to find an different way to play pirated HLA without VR?

**Comment by r57zone** [comment]
Yes, just try another version or another crack and the problem will go away.

**Comment by MixailTheDumbass** [comment]
Well. here goes 2 hours of downloading another crack.
