### ISSUE TITLE
Wolfenstein Cyberpilot/DOOM VFR issue

### ISSUE THREAD

**Issue by sos987** [r57zone/Half-Life-Alyx-novr#41]
Hi, The driver is working quite well for VR Wolf & doom thank you for that!
Still, some issues appear, maybe you have some suggestions on how to fix them?
1. Both Wolf&Doom: no sound at all
2. Both Wolf&Doom: not possible to open menu in-game, maybe some tricky key combination could help?
3. Doom only: movement/teleport not working, maybe some tricky key combination could help?
Thank you!

**Comment by r57zone** [comment]
Hi, 
1. Try changing the sound output in SteamVR settings
2.  Unfortunately I did not play them, I do not know how to open the menu. Try the buttons Numpad 0, Numpad del, Escape, Enter. Maybe they need to be combined, for example, with a trigger (RShift or Left mouse click).
3. Unfortunately, I don’t know either, but it seems that in Doom VFR, for some, it worked without problems.

**Comment by sos987** [comment]
Hi,
Thank you for reply! 
1. Sound is working like a charm by manually chosen audio output (but still no alt-tab allowed to game window out from headset window)
2. Menu button is minor so could be ignored
3. Some tuning over controller settings provides good result, so the game movement is ok and game is confirmed to be playable. Image of the settings for your reference: https://ibb.co/Gnx1t6D

**Comment by rogergithubbing** [comment]
Hello ! I have also no sound on wolfestein, and I think I've correctly followed the indications to manually set the sound, but it didn't work. Could you please post here the exact steps you followed to make it work for you ? Thanks in advance !
