### ISSUE TITLE
Game doesn't start in Headset Window

### ISSUE THREAD

**Issue by Nixinova** [r57zone/Half-Life-Alyx-novr#42]
When I start the game, SteamVR's Headset Window and overlay appear, but the Headset Window (which [SETUP.md#6](https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/SETUP.md) says should be the main program) only shows a black screen, and the game shows up in its normal window. The game in the normal window is extremely bugged and barely playable as the screen hardly adapts to mouse movement. Is there any way to fix this?

![NoHeadsetWindow](https://user-images.githubusercontent.com/42429413/86099677-edfc7100-bb0b-11ea-9c8d-5b314a7ab4e4.png)

**Comment by r57zone** [comment]
https://github.com/r57zone/Half-Life-Alyx-novr#troubleshooting
>Don't start in VR (Headset Window) mode - add the **-vr** launch option in the Steam game options or in the properties of the Windows shortcut.

**Comment by Nixinova** [comment]
It does use the `-vr` launch option.

**Comment by r57zone** [comment]
Try switching to the "Headset Window" and clicking inside.

**Comment by Nixinova** [comment]
I do, its permanently black.

**Comment by r57zone** [comment]
What is your monitor resolution? Have you tried manually specifying renderWidth, renderHeight? It should be like the resolution of your monitor.

**Comment by Nixinova** [comment]
Aha! That worked! (`"renderHeight" : 1440, "renderWidth" : 900`) But now the Headset Window is locked in 1:1; how can I fix that?

**Comment by r57zone** [comment]
If your monitor is 2560 by 1440, then you should set renderWidth 2560, renderWidth 1440.

**Comment by Nixinova** [comment]
Ah 🤦 yup, got them mixed around. Thanks man, this project is amazing!
