### ISSUE TITLE
System Wide Freeze - Workshop Tools only.

### ISSUE THREAD

**Issue by Moofers** [r57zone/Half-Life-Alyx-novr#43]
If running the hammer editor and running a map it'll lockup the entire system if the level is compiled and played. It seems random to when this happens. Didn't happen on old drivers (novr drivers). 

This when running the tools through VR mode.

**Comment by r57zone** [comment]
Unfortunately I don't know what this is connected with. It seems that this cannot be somehow related to the driver.

**Comment by Moofers** [comment]
Only happened once this driver was installed, unsure why its locking up though.
Seems to happen in main game to, it'll lock up the headset window but nothing else.

**Comment by Moofers** [comment]
Like to update that the old drivers cause this as well but not as frequent as this. Not sure why plays fine when in main game?

I've reseated my graphics card just incase.
