### ISSUE TITLE
Key bindings don't work like they used to.

### ISSUE THREAD

**Issue by ShadowGamer898** [r57zone/Half-Life-Alyx-novr#44]
Having issues with my numpad mimicking my keyboard keys and cannot seem to eject the magazine of the gun with the './del' button on my numpad nor can i use the '0/ins' key for other guns in the game. They will just either hold the gun like the 'del' key does or make the hands extend out further like the 'ins' key does...but they aren't different to the numpad keys. Any solutions?

**Comment by r57zone** [comment]
Use a different key profile or assign other buttons yourself.

**Comment by ShadowGamer898** [comment]
How do I assign buttons?

**Comment by r57zone** [comment]
https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/BINDINGS.md
