### ISSUE TITLE
Режим зрителя

### ISSUE THREAD

**Issue by GFOXSH** [r57zone/Half-Life-Alyx-novr#45]
Добрый день! Возникли проблемы с режимом зрителя в Half-Life: Alyx- "шлем" поворачивается с катастрофической задержкой, хотя "руки" при этом движутся спокойно. Скажите, пожалуйста, можно ли это как-нибудь поправить и, если нет, то какую версию игры посоветуете, в которой оно нормально работает? Тестировал на текущей стимовской версии и на 1.2.1 с торрентов. Заранее благодарю!

P. S. Проблема точь-в-точь как [здесь](https://github.com/r57zone/Half-Life-Alyx-novr/issues/24) но предложенный способ исправления не сработал.

**Comment by r57zone** [comment]
Добрый, да у некоторых возникает проблема с окном зрителя, вроде в последних версиях это перестало работать. Можно играть в "Headset Window", а для раскладки WASD перед запуском игры переключиться на русскую раскладку, тогда не возникнет проблем. Для HUD просто нажимаем на кнопку показа руки и на ней вся информация.

Можно еще попробовать отключить сглаживание камеры в настройках, попробовать.

**Comment by GFOXSH** [comment]
В Headset оно конечно работает, но раздражают черные скачки экрана и то, что если несколько минут не прикасаться к клавомыши экран заливает красным... Да и случайное нажатие "не туда" тоже особого удовольствия не доставляет. Скажите, пожалуйста, на какой версии Вы тестируете (и снимаете на Youtube) игру в режиме наблюдателя?

**Comment by r57zone** [comment]
1.2.0
Чтобы красным не заливался в настройках SteamVR можно увеличить время отключения вр шлема при бездействии.

**Comment by GFOXSH** [comment]
@r57zone разрешите уточнить - это сборка 4831658?

**Comment by r57zone** [comment]
К сожалению, не знаю, переустанавливал недавно Windows (вместе с играми).

**Comment by GFOXSH** [comment]
Понял. В общем, на 4831658 та же история, а более ранние я что-то не могу найти... Видимо, не суждено в режиме зрителя поиграть...
