### ISSUE TITLE
Will this mod work with regular VR HMD's like WMR to play without VR controllers ?

### ISSUE THREAD

**Issue by dusan-t** [r57zone/Half-Life-Alyx-novr#46]
Hi and thank you for making this mod. I was wondering if this mod can be used with regular VR HMD's like Windows Mixed Reality to play without VR controllers but still in VR, only with keyboard & mouse instead of regular VR controllers ?

**Comment by r57zone** [comment]
Hi yes it should work. It is necessary to disable the fake helmet from the driver and there will be only controllers.

https://github.com/r57zone/Half-Life-Alyx-novr#mobile-and-diy-vr-hmd
>For the new method....

https://youtu.be/Uq12rW3DrKI?t=178
