### ISSUE TITLE
Не получается ложить чтото в рюкзак 

### ISSUE THREAD

**Issue by iocmet** [r57zone/Half-Life-Alyx-novr#49]
Как ложить смолу и боеприпасы в рюкзак и доставать их?

**Comment by r57zone** [comment]
Подтягиваешь предмет, не отпускай кнопки жмешь на кнопку рюкзака и отпускаешь сначала подтягиванием, а потом кнопку рюкзака https://youtu.be/awDLnNq8klQ?t=268
Правый шифт и знак вопроса
