### ISSUE TITLE
Is there a way to use No-vr mod with real controllers, but without HMD?

### ISSUE THREAD

**Issue by goutosama** [r57zone/Half-Life-Alyx-novr#51]
Someone might have motion controllers (like PS Move) and with help of some drivers they can be used as controllers in Steam VR.
I thought it's possible to make layout where one controller could manage HMD movements (while holding specific button) and another one would use in-game teleportation to move character. In that way you wouldn't need any headset, just a screen and two controllers.
So I suggest a functions for this mod: remapping Headset controls and disabling built-in virtual Vive controllers.

**Comment by goutosama** [comment]
Можно и по-русски, если что.
Под словами without HMD я имел ввиду вывод изображения на экран монитора с возможностью поворачивать камеру.

**Comment by r57zone** [comment]
Привет, идея классная, сам тоже много об этом думал, но реализовать несколько типов управления непросто, ну и я уже наверное закончил с этим проектом.

Вместо шлема кстати можно использовать андроид смартфон или просто закрепить его куда-нибудь на тело или руку, выключить стерео в драйвере и будет монокартинка на мониторе, но при этом можно будет вертеть взглядом.

Также можно попробовать назначить клавиши клавиатуры на PSMove-ы, а на гироскоп повесить мышь.
