### ISSUE TITLE
Headset window freezes

### ISSUE THREAD

**Issue by Minxbin** [r57zone/Half-Life-Alyx-novr#53]
Hello I have a big issue the window freezes and I can't fix it 
and if I click my mouse it goes out of the window I did plug my other monitor out but doesn't work at all 
can someone please help?
Thank you
Marnes

**Comment by r57zone** [comment]
Hello, is the Headset Window freezing? Half Life crashes? 

Did you follow this instruction? 
https://www.youtube.com/watch?v=Uq12rW3DrKI
https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/SETUP.md#new-method
