### ISSUE TITLE
No sound inside some games

### ISSUE THREAD

**Issue by rogergithubbing** [r57zone/Half-Life-Alyx-novr#54]
Hi,

I don'k know if that's related to this driver, but I get no sound for the game you put as an example of other working games: Wolfestein Cyberpilot: Once the video intro at the beginning ends, I get no sound, no matter the audio option I choose from inside the game config itself.

Thanks in advance!

**Comment by r57zone** [comment]
Hi, try changing your sound card in SteamVR settings.

**Comment by rogergithubbing** [comment]
> 
> 
> Hi, try changing your sound card in SteamVR settings.

Hello,
Thanks, but it didn't work. Tried also to use an external usb audio card, with the same result. Also tried all the suggestions mentioned here: https://www.youtube.com/watch?v=U5QsbAkEtHU&t=248s

Can you please test it with this game ? Your driver works correctly with Alyx,  but not with this game; It's maybe specific to it...

**Comment by r57zone** [comment]
You can also try to enable audio duplication on a second sound card. Probably a problem with the game, as there is no mention of a sound card in the driver. Unfortunately, I do not know what could be fixed.

**Comment by rogergithubbing** [comment]
> You can also try to enable audio duplication on a second sound card. Probably a problem with the game, as there is no mention of a sound card in the driver. Unfortunately, I do not know what could be fixed.

Thanks again... 8'd tried also with audio duplication and getting audio also from the monitor (hdmi); Nothing worked... It's very strange... Can anybody test it ?

**Comment by r57zone** [comment]
Probably, I cannot help with this, since the driver does not use sound in any way and SteamVR itself does this.
