### ISSUE TITLE
растянутое изображение

### ISSUE THREAD

**Issue by Pantelina60** [r57zone/Half-Life-Alyx-novr#55]
У меня какое-то некорректное изображение. Нативное разрешение монитора - 1366x768. В настройках драйвера прописал это значение. Но изображение все равно неккоректное
![Screenshot (4)](https://user-images.githubusercontent.com/79439434/128638608-5039847e-a256-45ea-9a72-7b71b566e0b2.png)
![Screenshot (5)](https://user-images.githubusercontent.com/79439434/128638614-b77c38d4-8c4a-488c-bb19-cc60730408d0.png)

**Comment by r57zone** [comment]
Значение FOV я вижу было изменено, а если вернуть на 110? как в игре выглядит?
Так и используется старый драйвер, попробуйте новый - https://youtu.be/Uq12rW3DrKI
Папку tovr из steam drivers удалить

**Comment by Pantelina60** [comment]
> Значение FOV я вижу было изменено, а если вернуть на 110? как в игре выглядит?
> Так и используется старый драйвер, попробуйте новый - https://youtu.be/Uq12rW3DrKI
> Папку tovr из steam drivers удалить

обновил драйвер, изменил фов, но все равно такое изображение, также я изменил зум (ширина высота на 0.8). не помогло.
UPD: более того, я изменил windowHeight/Width на 800x600 - итога нету. все равно растянутое изображение
UPD2: удалил hlalyx драйвер целиком и закинул нетронутый, толку ноль. походу не здесь это настраивается

**Comment by r57zone** [comment]
Попробуй render height изменить, написать 800, 900, по высоте растянуто? на картинке не особо видно

**Comment by Pantelina60** [comment]
> Попробуй render height изменить, написать 800, 900, по высоте растянуто? на картинке не особо видно

Растянуто по высоте

**Comment by r57zone** [comment]
Смена renderHeight не помогает? увеличение с 768

**Comment by Pantelina60** [comment]
я пришел к выводу что любое изменение высоты или ширины в render или window никак не влияет. Я могу только через сам SteamVR изменить масштаб рендера и угол обзора. это странно....очень

**Comment by Pantelina60** [comment]
Пофиксил

**Comment by r57zone** [comment]
Как удалось исправить?

**Comment by Pantelina60** [comment]
Точно сказать не могу, но я решил удалить халфу ( у меня от хатаба), переустановил SteamVR, и затем скачал sublime text, и мне кажется что все стало на свои места после того как я отредактировал файл с настройками через sublime, а не через обычный блокнот. Также я поиграл с раскладкой, и изображение стало нормальное. Короче я сам не понял, но все стало нормально!
