### ISSUE TITLE
How to do two actions: Grab from backpack and store in backpack

### ISSUE THREAD

**Issue by rogergithubbing** [r57zone/Half-Life-Alyx-novr#56]
Hi,

I cannot guess the key combinations to grab the ammo from the backpack, can you please help me ?

Also, I've stored the amo once in the backpack, but sincerely, I don't know how the hell I was able to do it. I would need also some help.

Thanks !

**Comment by r57zone** [comment]
Hi, first you need to press "?", And then Right Shift to take something, and to put it you need to take the item in your left hand, press "?" and lower Shift. 
https://youtu.be/uO7iFsKial0?t=875

**Comment by rogergithubbing** [comment]
Hello... Yes, of course you are right, the problem was on my side: I am using US Keyboard with the Spanish settings in Windows, because if not, I would not be able to use accent marks needed for Spanish; Also I'm using autohotkey to set some special keys. So, that "?" key was not really the real "?". Once the regional settings in Windows are set to EN-US and the autohotkey is disabled, everything works. I was doubting about myself, because I'd already tried your suggestion. Things happen for a reason.

Thanks again !

**Comment by r57zone** [comment]
Сan customize the keys for yourself, make it more convenient if necessary 
https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/BINDINGS.md
