### ISSUE TITLE
Перестали притягиваться предметы на Shift

### ISSUE THREAD

**Issue by Pantelina60** [r57zone/Half-Life-Alyx-novr#57]
Правая рука притягивает, левая почему то нет. При нажатии shift она сжимается, все действия работают кроме притягивания.

**Comment by r57zone** [comment]
Для Steam переходим в свойствах игры, там жмем параметры запуска и вводим +vr_gg_gesture_pull 0. Для обычного ярлыка заходим в свойства ярлыка и добавляем тоже самое: "C:\Games\Half-Life Alyx\bin\win64\hlvr.exe" +vr_gg_gesture_pull 0. Это нужно чтобы предметы подтягивались по одной кнопке.
https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/SETUP2.RU.md#%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4

Это сделано?

**Comment by Pantelina60** [comment]
Да. Я ещё откатился на более старое сохранение, где обе руки работали, но потом перестала притягивать другая рука. Застрял на 3 главе

**Comment by Pantelina60** [comment]
В итоге я не могу после модернизации оружия забрать его. Она как будто перестала взаимодействовать с предметами. Она только двигать может и все.

**Comment by Pantelina60** [comment]
Все исправилось. Это был  баг. Все это время рука как бы держала другой предмет который застрял.
