### ISSUE TITLE
Как прикрепить фонарик к левой перчатке?

### ISSUE THREAD

**Issue by Pantelina60** [r57zone/Half-Life-Alyx-novr#58]
Не понимаю как это сделать, ведь правая рука ограничена в движениях. Левой то можно, но игра требует именно к левой перчатке

**Comment by Pantelina60** [comment]
Левую руку нужно поднести к правой

**Comment by r57zone** [comment]
Если что-то не получается можно посмотреть видео на ютубе, на канале есть все механики и подсказки по прохождению.
