### ISSUE TITLE
Doesn't work with Valve Index

### ISSUE THREAD

**Issue by slambo312** [r57zone/Half-Life-Alyx-novr#61]
Whenever I open something like Aperture Hand Lab, my hands don't do shit.

**Comment by r57zone** [comment]
Hi, the headset Window must be in focus and I also think it is possible to disable HMD in the driver (read the instructions for Mobile VR or the video instruction, there you need to change 1 parameter in the config) 
https://youtu.be/4Q_YqkWfWqI

**Comment by r57zone** [comment]
> it is necessary to change the HMD parameter to 0 in the configuration file "...\Steam\steamapps\common\SteamVR\drivers\hlalyx\HalfLifeAlyx.ini" and install the necessary SteamVR driver for the HMD.
