### ISSUE TITLE
Weird key bindings

### ISSUE THREAD

**Issue by Kashuk0** [r57zone/Half-Life-Alyx-novr#63]
Instead of wasd, the middle mouse wheel is used to move forward, N and M to move left and right, and spacebar to move backward, what did I do wrong? and where is the file  "HalfLifeAlyx64.dll"?

**Comment by r57zone** [comment]
HalfLifeAlyx64.dll is no longer required. Maybe you have some specific keyboard codes. Try to customize it yourself or try a different layout, you can do this by following the instructions or video.

**Comment by r57zone** [comment]
https://github.com/r57zone/Half-Life-Alyx-novr#setup
Use KeyCodeTool to find out your key code.

**Comment by r57zone** [comment]
Also in the archive you can find other layouts, maybe that can be placed here ...\Steam\steamapps\common\SteamVR\drivers\hlalyx
