### ISSUE TITLE
как кинуть энергетический шар? Ни одна кнопка не работает

### ISSUE THREAD

**Issue by OlegMonsterKill** [r57zone/Half-Life-Alyx-novr#64]

**Comment by r57zone** [comment]
Надо нажимать много раз клавишу End https://youtu.be/scb2l8eF5s4 
Механика кривая, у меня и на VR контроллерах проблема с этим.
https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/README.RU.md#%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5

**Comment by OlegMonsterKill** [comment]
у меня получилось резким движением в сторону кинуть при этом ничего не нажимая
