### ISSUE TITLE
Controls?

### ISSUE THREAD

**Issue by JimmisAtha** [r57zone/Half-Life-Alyx-novr#65]
Well.... You got a really nice work, I dont have vr. TrueOpenVR worked best for me, but the controls remain difficult.... The mouse sensitivity is too high, and I can't center the aim (keeps autorotating). Controls could be also asigned same as source engine (wasd, f, )

**Comment by r57zone** [comment]
Setup https://github.com/r57zone/Half-Life-Alyx-novr#setup 
https://www.youtube.com/watch?v=Uq12rW3DrKI
WASD keys - https://youtu.be/awDLnNq8klQ
