### ISSUE TITLE
No pause menu

### ISSUE THREAD

**Issue by febryce** [r57zone/Half-Life-Alyx-novr#67]
Hi,

When I press ESC the cursor stays stuck in the center of the screen. 
I can't get the pause menu to go into the settings. 

I am Belgian but I have put my keyboard in English. 

What is the solution?

Thanks

**Comment by r57zone** [comment]
Hi, https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/BINDINGS.md

**Comment by febryce** [comment]
> Hi, https://github.com/r57zone/Half-Life-Alyx-novr/blob/master/BINDINGS.md

Hi Boss !

I already consulted this link but unfortunately it doesn't help me.

I don't know which action to replace in HalfLifeAlyx.ini?

**Comment by r57zone** [comment]
Replace "Left Controller Grip" code , you can find out the button code in a separate utility that comes with the bundle archive.

**Comment by r57zone** [comment]
in HalfLifeAlyx.ini

**Comment by febryce** [comment]
> 
It's "LEFT_GRIP=" ?

it's this action that I modify but nothing changes in the game. 
The problem is somewhere else but I don't understand where.

- I installed SteamVR + configured on a small room in 1.70m. I deactivated Steam Home.
- I copied the folder of the "hlalyx" in the folder "drivers" of SteamVR.
- I created a shortcut to the .exe and added the command "+vr_gg_gesture_pull 0"

**Comment by febryce** [comment]
I wonder, this is not a legit game. I downloaded it. Is that the problem ?

**Comment by r57zone** [comment]
Find this line in "HalfLifeAlyx.ini", replace 27 with another number (the number corresponds to a button on the keyboard, you can find out the number by opening the archive and running the program "tools/KeyCodeTool.exe")
```
[Keys]
LEFT_GRIP=27
```
Description of actions and buttons is here - https://github.com/r57zone/Half-Life-Alyx-novr#control

Any copy of the game will do, pirated or licensed, it doesn't matter.

After all the changes, restart SteamVR and the game.

The installation process is described here - https://github.com/r57zone/Half-Life-Alyx-novr#setup

**Comment by febryce** [comment]
> Trouvez cette ligne dans "HalfLifeAlyx.ini", remplacez 27 par un autre numéro (le numéro correspond à un bouton du clavier, vous pouvez trouver le numéro en ouvrant l'archive et en exécutant le programme "tools/KeyCodeTool.exe")
> 
> ```
> [Keys]
> LEFT_GRIP=27
> ```
> 
> La description des actions et des boutons est ici - [https://github.com/r57zone/Half-Life-Alyx-novr#control ](https://github.com/r57zone/Half-Life-Alyx-novr#control)
> 
> N'importe quelle copie du jeu fera l'affaire, piratée ou sous licence, peu importe.
> 
> Après tous les changements, redémarrez SteamVR et le jeu.
> 
> Le processus d'installation est décrit ici - [https://github.com/r57zone/Half-Life-Alyx-novr#setup ](https://github.com/r57zone/Half-Life-Alyx-novr#setup)



That's the problem, I've done everything you mention and it doesn't work 🤯

**Comment by r57zone** [comment]
Steam VR Headset Window escape works, Spectator mode doesn't
