### ISSUE TITLE
Quest 2 touch controllers + keyboard

### ISSUE THREAD

**Issue by robegamesios** [r57zone/Half-Life-Alyx-novr#68]
Hi can i use your driver to simultaneously use quest 2 touch controllers and the keyboard? I am building a VR haptic gun and I want to map the weapon select/deselect to buttons connected to esp32 wroom dev board. what steps do I need to do? thanks in advance

**Comment by r57zone** [comment]
Hi, not with this driver, but with this you can https://github.com/r57zone/OpenVR-Additional-Arduino-Btns (in debug mode)

**Comment by robegamesios** [comment]
thanks! Here is my project in case you are interested. https://github.com/robegamesios/VRHapticGun. will post a video soon
