### ISSUE TITLE
Headset Window not showing

### ISSUE THREAD

**Issue by r57zone** [r57zone/Half-Life-Alyx-novr#75]
Headset Window is no longer showing after the update SteamVR
https://github.com/ValveSoftware/openvr/issues/1780

As a temporary solution, you can use an old version of SteamVR.
1. Uninstall the current SteamVR.
2. [Unzip this file](https://github.com/r57zone/VR-tracking-apps/releases/download/1/SteamVR.1.18.31.07.21.7z) to C:\Program Files\SteamVR.
3. Run "vrstartup.exe".

**Comment by r57zone** [comment]
As a temporary solution, you can use an old version of SteamVR.
1. Uninstall the current SteamVR.
2. [Unzip this file](https://github.com/r57zone/VR-tracking-apps/releases/download/1/SteamVR.1.18.31.07.21.7z) to C:\Program Files\SteamVR.
3. Run "vrstartup.exe".

**Comment by l4v3nx** [comment]
where exactly is this executable? in zip or in steamvr 2.0 steam folder?

**Comment by r57zone** [comment]
In zip

**Comment by r57zone** [comment]
The problem is fixed in beta 2.2.1  - https://store.steampowered.com/news/app/250820/view/3873722126474526180
