### ISSUE TITLE
Steam Vr update broke the mod

### ISSUE THREAD

**Issue by something100** [r57zone/Half-Life-Alyx-novr#76]
after the 2.0 update came out for steam vr the headset window no longer opens so the mod is no longer playable.

**Comment by r57zone** [comment]
Yeah, that's right, I hope they fix the problem, but there are already half life no vr mods that don't use VR emulation, you can try them.
https://github.com/r57zone/Half-Life-Alyx-novr/issues/75
https://github.com/ValveSoftware/openvr/issues/1780
