### ISSUE TITLE
Mobile and DIY VR with HMD rotation

### ISSUE THREAD

**Issue by jR4v** [r57zone/Half-Life-Alyx-novr#79]
Доброго времени суток.

Я прошу прощения, если это где-либо описано, но поиском не нашёл, а сам данный пункт в инструкции нахожу не совсем интуитивно понятным.

![image](https://github.com/user-attachments/assets/687e8126-720c-4297-a60e-71b7c3568c15)

Где и как необходимо внести эти изменения?

**Comment by r57zone** [comment]
Привет, профили кнопок в архиве драйвера, в папке `HalfLifeAlyx.1.1.SteamVR.driver.zip\Other keys bindings\Mobile and DIY VR with HMD rotation\`. Нужно скопировать файл и перенести в папку стима (файл соотношений кнопок), там же можно прочитать ReadMe, в котором описаны измененные кнопки.

**Comment by jR4v** [comment]
Большое спасибо. Прошу прощения за свою невнимательность.
