### ISSUE TITLE
Все?

### ISSUE THREAD

**Issue by IceCrunk** [r57zone/Half-Life-Alyx-novr#8]
после послед обновы на 70 мб (только что выбило из игры) перестало заходить пишет теперь пройдите какую то ферификацию вр походу пофиксили)

**Comment by r57zone** [comment]
Обновился Half Life или SteamVR?

**Comment by IceCrunk** [comment]
халфа

**Comment by r57zone** [comment]
А можно видос какой-нибудь там? Странно конечно

**Comment by IceCrunk** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1013815632341484191/E329E782EE316FF2830067B7C6D827DAEC412C08/ вот такая ошибка вылетает теперь при запуске

**Comment by IceCrunk** [comment]
Попробую по новой сейчас переустановить по всем пунктам мб поможет..

**Comment by IceCrunk** [comment]
Вообщем не понятно в чем дело, но теперь стимвр не видит как бы шлем.. 2 контролера активны, а шлем нет из за этого вся проблема..

**Comment by r57zone** [comment]
А до обновления точно все работало? Разрешения в конфигах стоят такие же как у монитора?

**Comment by IceCrunk** [comment]
Настройки все правильные. Да до обновления пол игры прошел.. потом выбило, все закрылось и игра и стимвр и вот теперь как бы шлем не видит.

**Comment by IceCrunk** [comment]
Пишет, что шлем в режиме ожидания "пошевелите шлемом для актицвации"))

**Comment by r57zone** [comment]
Шлем шевелится когда окно "Headset Window" в фокусе, то есть активно. На всякий забекапить сейфы нужно и если что пройти на пиратке.
Можно еще попробовать переставить стимвр, перезагрузить пк.

**Comment by IceCrunk** [comment]
Ок. Спс. Да вроде уже все перепробовал..

**Comment by r57zone** [comment]
Если они что-то сделали, то я не знаю как это можно было подчинить, но вроде по ошибке не похоже, чтобы они верификацию какую-то сделали.
Вроде и из игр никогда не выбивает когда обновление приходит, а обновляется когда закрыта.
В общем не знаю.

**Comment by r57zone** [comment]
Я спросил человека с лицензией, он говорит, что ничего не поменялось, так что проблема по видимому в другом.

**Comment by IceCrunk** [comment]
Все перепробовал и полную переустановку заного, при запуске вылетает такое окно https://steamuserimages-a.akamaihd.net/ugc/1013815685487993786/573D69DF706002366297F51DEC59E4AFB148B279/

**Comment by IceCrunk** [comment]
Фух разобрался, не знаю почему, но помогли эти драйвера https://store.steampowered.com/app/992490/iVRy_Driver_for_SteamVR/ все заработало как поставил.
